CREATE TABLE IF NOT EXISTS books(
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `path` VARCHAR(255) NOT NULL,
    `full_path` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `type` VARCHAR(100) NOT NULL,
    `scanned_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `last_scanned_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)